// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYP2aEZSjsXYCE8EXQXf_SKyDP3DTtqMc',
    appId: '1:190431537371:web:15c91140b3a153944e04fe',
    messagingSenderId: '190431537371',
    projectId: 'jjapstagram-ff480',
    authDomain: 'jjapstagram-ff480.firebaseapp.com',
    storageBucket: 'jjapstagram-ff480.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvzG0JY8MDHG9H0XEGY0imPK12ARkQa-4',
    appId: '1:190431537371:android:eadfd58ba6176ac74e04fe',
    messagingSenderId: '190431537371',
    projectId: 'jjapstagram-ff480',
    storageBucket: 'jjapstagram-ff480.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5PQmB5LlF3_BvLwEmUx-Fs04vTsQDKDA',
    appId: '1:190431537371:ios:d6524ebdcdcc45d84e04fe',
    messagingSenderId: '190431537371',
    projectId: 'jjapstagram-ff480',
    storageBucket: 'jjapstagram-ff480.appspot.com',
    iosBundleId: 'com.example.jjapstagram',
  );

}